### ISSUE TITLE
Update bs-jest to @glennsl/bs-jest

### ISSUE THREAD

**Issue by oshimayoan** [reasonml-community/reason-scripts#46]
Is there any plan to update current bs-jest which is already deprecated to the latest @glennsl/bs-jest?
Source: https://github.com/glennsl/bs-jest#bs-jest

**Comment by rrdelaney** [comment]
Should be done in 1.0. I'm super busy with work right now, and haven't had time for a lot of these things recently 😕

**Comment by oshimayoan** [comment]
I think I could help you with this but still don't know the right way to test the scripts.

I tried this:
```
yarn create react-app testApp --scripts-version https://github.com/oshimayoan/reason-scripts/archive/reason-scripts-updated-bs-jest.tar.gz
```
But always got this same error:
```
Aborting installation.
Unexpected error. Please report it as a bug:
{ Error: Cannot find module '/Users/Me/projects/opensource/test/node_modules/reason-scripts-updated-bs-jest/package.json'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at checkNodeVersion (/Users/Me/.config/yarn/global/node_modules/create-react-app/createReactApp.js:514:23)
    at getPackageName.then.then.then.packageName (/Users/Me/.config/yarn/global/node_modules/create-react-app/createReactApp.js:312:7)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'MODULE_NOT_FOUND' }
```

**Comment by rrdelaney** [comment]
It’s a little difficult to test locally, and I haven’t really figured out a way other than to deploy alpha versions 😕 sorry, development is a little difficult right now..
